src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url_video = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    
    #[ORM\ManyToMany(targetEntity: Mood::class, inversedBy: 'movies')]
    #[ORM\JoinTable(name:"movie_mood"), JoinColumn(name:"movie_id", referencedColumnName:"id"),
    inverseJoinColumns(name:"mood_id", referencedColumnName:"id")
    ]
    private Collection $moods;

    #[ORM\ManyToMany(targetEntity: Mood::class)]
    private $mood;

    public function __construct()
    {
        $this->moods = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUrlVideo(): ?string
    {
        return $this->url_video;
    }

    public function setUrlVideo(?string $url_video): self
    {
        $this->url_video = $url_video;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, mood>
     */
    public function getMoods(): Collection
    {
        return $this->moods;
    }

    public function addMood(Mood $mood): self
    {
        if (!$this->moods->contains($mood)) {
            $this->moods->add($mood);
        }

        return $this;
    }
    
    public function removeMood(Mood $mood): self
    {
        $this->moods->removeElement($mood);

        return $this;
    }

    public function getMood(): ?Mood
    {
        return $this->mood;
    }

    public function setMood(?Mood $mood): self
    {
        $this->mood = $mood;

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
}

src/Controller/MovieDetailController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Movie;

class MovieDetailController extends AbstractController
{

    #[Route('/movie-detail/{id}', name: 'app_movie_detail')]
    public function index(EntityManagerInterface $entityManager, int $id): Response
    {
        $movie = $entityManager->getRepository(Movie::class)->findOneById($id);


        return $this->render(
            'movie_detail/index.html.twig',
            [
                'controller_name' => 'MovieDetailController',
                'movie' => $movie
            ]
        );
    }

    // Probablement inutile, mais exemple de logique ajoutant un movie dans la bdd directement depuis le serveur
    // #[Route('/addMovie', name: 'create_movie')]
    // public function createProduct(EntityManagerInterface $entityManager): Response
    // {
    //     $movie = new Movie();
    //     $movie->setTitle('Bonjour');
    //     $movie->setDescription('Ergonomic and stylish!');

    //     // tell Doctrine you want to (eventually) save the movie (no queries yet)
    //     $entityManager->persist($movie);

    //     // actually executes the queries (i.e. the INSERT query)
    //     $entityManager->flush();

    //     return new Response('Saved new movie with id '.$movie->getId());
    // }
}

templates/movie_detail/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Movie Detail
{% endblock %}

{% block stylesheets %}
	{{ encore_entry_link_tags('app') }}
{% endblock %}


{% block body %}

	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #070E2D;
			text-align: center;
		}
		h1 {
			font-size: 36px;
			color: #536EE4;
			margin-bottom: 22px;
		}
		h2 {
			font-size: 24px;
			color: #536EE4;
			margin-bottom: 5px;
		}
		p {
			font-size: 18px;
			color: white;
			line-height: 1.5;
			margin-bottom: 20px;
			padding: 1rem;
		}
		.genre {
			background-color: white;
			padding: 15px 10px;
			border-radius: 5px;
			display: inline-block;
			margin-right: 10px;
			font-size: 16px;
			color: #536EE4;
			font-weight: bold;
			margin-top: 1rem;
		}

		img {
			width: 250px;
			border-radius: 8px;
		}
		iframe {
			margin-bottom: 100px;
		}
		iframe:hover {
			width: 1050px;
			height: 600px;
			margin-bottom: 0;
			/* transform: scale(3); */
			transition: 1s;
		}
		.return-list a {
			color: #fff;
			text-decoration: underline;
			text-underline-offset: 3px;
		}
	</style>
</head>

<body>
	<div class="return-list">
		<a href="{{ path('app_movies_list')}}">Retour à la liste</a>
	</div>
	<h1>{{movie.title}}</h1>
	<img src="{{ movie.picture }}" alt="" width="200px">
	<br>
	<div class="genre">Action</div>
	{% for mood in movie.moods %}
		<p>{{ mood.name }}</p>
	{% endfor %}
	<div class="genre">Adventure</div>
	<div class="genre">Science Fiction</div>
	<h2>Publication Date:</h2>
	<p>{{ movie.date ? movie.date|date('Y-m-d') : '' }}</p>
	<h2>Description:</h2>
	<p>{{movie.description}}</p>
	<p>Vidéo :</p>
	<iframe width="350px" height="200px" src="{{ movie.urlVideo }}" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
	<div class="return-list">
		<a href="{{ path('app_movies_list')}}">Retour à la liste</a>
	</div>
	<br>
	<br>
</body> 
{% endblock %}